[package]
name = "room-demo"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "room-demo"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.5"